parameters:
    #The system code for your product
    health_check.system_code: ''

    #The human readable name your product
    health_check.name: ''

    #The description of your product
    health_check.description: ''

    health_check.cache_pool: 'ezpublish.cache_pool'

    health_check.run_first: true
