services:
    health_check.controller:
        class: FT\HealthCheckBundle\Controller\HealthCheckController
        public: true
        arguments:
            - '@health_check.factory'
            - '@health_check.registry'
            - '@health_check.service.executor'

    health_check.factory:
        class: FT\HealthCheckBundle\Factory\HealthCheckResponseFactory
        arguments:
            - '%health_check.system_code%'
            - '%health_check.name%'
            - '%health_check.description%'
            - '@monolog.logger'

    health_check.service.cache:
        class: FT\HealthCheckBundle\Service\CachedHealthCheckService
        arguments:
            - '@monolog.logger'
            - '@service_container'
        calls:
            - [setCachePoolFromServiceId, ["@=container.hasParameter('health_check.cache_pool') ? parameter('health_check.cache_pool') : ''"]]
        
        # Lazy load service to fix a an issue where the run_first option was not being respected as a connection to the
        # configured cache pool was being opened when dependency injecting health_check.service.cache to other services.
        lazy:  true
    health_check.service.executor:
        class: FT\HealthCheckBundle\Service\HealthCheckExecutorService
        arguments:
            - '@health_check.service.cache'

    health_check.registry:
        class: FT\HealthCheckBundle\HealthCheck\HealthCheckRegistry